# Generated by Django 4.1.5 on 2024-06-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
    ]
