# Generated by Django 4.1.5 on 2024-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_cliente_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
