# Generated by Django 4.2.13 on 2024-06-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
