# Generated by Django 4.2.13 on 2024-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_cliente_groups_cliente_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
