# Generated by Django 4.2.13 on 2024-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_categoria_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
