# Generated by Django 4.2.13 on 2024-06-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
